language: python
python:
  - "2.7"
# - "3.4"

sudo: false
dist: trusty
os:
  - linux

addons:
  apt:
    packages:
    - ttfautohint

install:
  - pip install -r requirements.txt

script:
  - make otf
  - make ttf
  - make vf
